### ISSUE TITLE
Naive Doubt regarding the Rust parsers

### ISSUE THREAD

**Issue by harrydevnull** [rusticata/rusticata#3]
can i use this project to validate the syntax of rules that are to be send across to suricata?
my intend is this; have a restful interface post the rule sets which gets validated using the above code.
is my understanding/question flawed?

**Comment by chifflier** [comment]
Hi,
This project is used to add and test code for parsers, not for testing rules. You should use suricata itself to test your rules (using pcap files, for ex).
