### ISSUE TITLE
nom version mismatched caused compile problems

### ISSUE THREAD

**Issue by copslock** [rusticata/rusticata#4]
Compiling rand_core v0.3.0
   Compiling libc v0.2.43
   Compiling siphasher v0.2.3
   Compiling version_check v0.1.5
   Compiling num-traits v0.2.6
   Compiling cfg-if v0.1.5
   Compiling cookie-factory v0.2.4
   Compiling rand_core v0.2.2
   Compiling memchr v1.0.2
   Compiling phf_shared v0.7.23
   Compiling memchr v2.1.0
   Compiling log v0.4.5
   Compiling rand v0.5.5

   Compiling nom v3.2.1

   Compiling phf v0.7.23
   Compiling log v0.3.9
   Compiling phf_generator v0.7.23
   Compiling rusticata-macros v0.3.3
   Compiling num-traits v0.1.43
   Compiling phf_codegen v0.7.23

   Compiling nom v4.0.0

   Compiling enum_primitive v0.1.1
   Compiling tls-parser v0.5.0
   Compiling rusticata-macros v1.0.0
   Compiling ntp-parser v0.1.5
   Compiling ssh-parser v0.1.2

In the same project 2 versions of nom were used,and caused a lot of compile errors

**Comment by copslock** [comment]
error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/openvpn.rs:31:17
   |
31 |                 IResult::Done(rem,r) => {
   |                 ^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], openvpn_parser::OpenVPNPacket<'_>), nom::internal::Err<&[u8]>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/openvpn.rs:61:12
   |
61 |     if let IResult::Done(_,_) = parse_openvpn_tcp(i) { return true; }
   |            ^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], openvpn_parser::OpenVPNPacket<'_>), nom::internal::Err<&[u8]>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/openvpn_udp.rs:31:17
   |
31 |                 IResult::Done(rem,r) => {
   |                 ^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], openvpn_parser::OpenVPNPacket<'_>), nom::internal::Err<&[u8]>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/openvpn_udp.rs:62:9
   |
62 |         IResult::Done(rem,pkt) => {
   |         ^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], openvpn_parser::OpenVPNPacket<'_>), nom::internal::Err<&[u8]>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/snmp.rs:25:13
   |
25 |             IResult::Done(_rem,r) => {
   |             ^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], snmp_parser::SnmpMessage<'_>), nom::internal::Err<&[u8]>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
  --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/snmpv3.rs:23:13
   |
23 |             IResult::Done(_rem,r) => {
   |             ^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
   |
   = note: expected type `std::result::Result<(&[u8], snmp_parser::SnmpV3Message<'_>), nom::internal::Err<&[u8], snmp_parser::error::SnmpError>>`
              found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:140:30
    |
140 |                             &IResult::Done(_,ref l) => {
    |                              ^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], std::vec::Vec<tls_parser::TlsExtension<'_>>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:207:33
    |
207 |                                 IResult::Done(_rem,x509) => {
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], x509_parser::X509Certificate<'_>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:279:13
    |
279 |             IResult::Done(rem2,ref msg_list) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], std::vec::Vec<tls_parser::TlsMessage<'_>>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:289:13
    |
289 |             IResult::Incomplete(needed) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], std::vec::Vec<tls_parser::TlsMessage<'_>>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:295:13
    |
295 |             IResult::Error(e) => { warn!("parse_tls_record_with_header failed: {:?}",e); status |= R_STATUS_FAIL; },
    |             ^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], std::vec::Vec<tls_parser::TlsMessage<'_>>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:331:17
    |
331 |                 IResult::Done(rem, ref r) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], tls_parser::TlsRawRecord<'_>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:336:17
    |
336 |                 IResult::Incomplete(needed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], tls_parser::TlsRawRecord<'_>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:342:17
    |
342 |                 IResult::Error(e) => { warn!("Parsing failed: {:?}",e); break },
    |                 ^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], tls_parser::TlsRawRecord<'_>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:500:17
    |
500 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], (tls_parser::ServerECDHParams<'_>, tls_parser::DigitallySigned<'_>)), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0609]: no field `0` on type `&_`
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:502:64
    |
502 |                     info!("Temp key: using cipher {:?}",parsed.0.curve_params);
    |                                                                ^

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:524:17
    |
524 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], (tls_parser::ServerDHParams<'_>, tls_parser::DigitallySigned<'_>)), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0609]: no field `0` on type `&_`
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:526:73
    |
526 |                     info!("Temp key: using DHE size_p={:?} bits",parsed.0.dh_p.len() * 8);
    |                                                                         ^

error[E0308]: mismatched types
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:536:17
    |
536 |                 IResult::Done(_,ref parsed) => {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::result::Result`, found enum `nom::IResult`
    |
    = note: expected type `std::result::Result<(&[u8], tls_parser::ServerDHParams<'_>), nom::internal::Err<&[u8]>>`
               found type `nom::IResult<_, _, _>`

error[E0609]: no field `dh_p` on type `&_`
   --> /root/.cargo/git/checkouts/rusticata-9023a77455e0d55a/e2ab6c4/src/tls.rs:538:73
    |
538 |                     info!("Temp key: using ADH size_p={:?} bits",parsed.dh_p.len() * 8);
    |                                                                         ^^^^

error: aborting due to 20 previous errors

Some errors occurred: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: Could not compile `rusticata`.

To learn more, run the command again with --verbose.

**Comment by chifflier** [comment]
There was a missing commit in openvpn-parser, and is fixed by https://github.com/rusticata/openvpn-parser/commit/fb63ff8b01de4a1bf6477645141c0561c5e6635d
