### ISSUE TITLE
[Request]Update documentation

### ISSUE THREAD

**Issue by Jgerardopine** [rusticata/rusticata#6]
Hi,
  On the README you are requesting to install pcap-parse, but apparently this has been deprecated in favor of pcap-analyzer. It would be good to mention that section is deprectaed and pcap-analyzer is the crate to install.
  Also, is there some function pcap-parse does that pcap-analyzer doesn't support?

**Comment by chifflier** [comment]
You're right, the README needs t be updated (will do).

About the features of both tools, `pcap-analyzer` has way more features than `pcap-parse`, which was more a toy project. `pcap-analyzer` provides both a framework to develop plugins, low-level code, and also applications. It has support for more protocols, and decodes them correctly.
